/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WriteRouteImport } from './routes/write'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterGoogleRouteImport } from './routes/register/google'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterGoogleRoute = RegisterGoogleRouteImport.update({
  id: '/register/google',
  path: '/register/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/posts': typeof PostsRoute
  '/profile': typeof ProfileRoute
  '/write': typeof WriteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/register/google': typeof RegisterGoogleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/posts': typeof PostsRoute
  '/profile': typeof ProfileRoute
  '/write': typeof WriteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/register/google': typeof RegisterGoogleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/posts': typeof PostsRoute
  '/profile': typeof ProfileRoute
  '/write': typeof WriteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/register/google': typeof RegisterGoogleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/members'
    | '/posts'
    | '/profile'
    | '/write'
    | '/auth/callback'
    | '/register/google'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/members'
    | '/posts'
    | '/profile'
    | '/write'
    | '/auth/callback'
    | '/register/google'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/members'
    | '/posts'
    | '/profile'
    | '/write'
    | '/auth/callback'
    | '/register/google'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  PostsRoute: typeof PostsRoute
  ProfileRoute: typeof ProfileRoute
  WriteRoute: typeof WriteRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  RegisterGoogleRoute: typeof RegisterGoogleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/google': {
      id: '/register/google'
      path: '/register/google'
      fullPath: '/register/google'
      preLoaderRoute: typeof RegisterGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  PostsRoute: PostsRoute,
  ProfileRoute: ProfileRoute,
  WriteRoute: WriteRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  RegisterGoogleRoute: RegisterGoogleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
