/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WriteRouteImport } from './routes/write'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImagesRouteImport } from './routes/images'
import { Route as DraftsRouteImport } from './routes/drafts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterGoogleRouteImport } from './routes/register/google'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'

const WriteRoute = WriteRouteImport.update({
  id: '/write',
  path: '/write',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImagesRoute = ImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsRoute = DraftsRouteImport.update({
  id: '/drafts',
  path: '/drafts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterGoogleRoute = RegisterGoogleRouteImport.update({
  id: '/register/google',
  path: '/register/google',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/drafts': typeof DraftsRoute
  '/images': typeof ImagesRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/write': typeof WriteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/register/google': typeof RegisterGoogleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/drafts': typeof DraftsRoute
  '/images': typeof ImagesRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/write': typeof WriteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/register/google': typeof RegisterGoogleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/drafts': typeof DraftsRoute
  '/images': typeof ImagesRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/write': typeof WriteRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/register/google': typeof RegisterGoogleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/drafts'
    | '/images'
    | '/login'
    | '/profile'
    | '/write'
    | '/auth/callback'
    | '/register/google'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/drafts'
    | '/images'
    | '/login'
    | '/profile'
    | '/write'
    | '/auth/callback'
    | '/register/google'
  id:
    | '__root__'
    | '/'
    | '/drafts'
    | '/images'
    | '/login'
    | '/profile'
    | '/write'
    | '/auth/callback'
    | '/register/google'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DraftsRoute: typeof DraftsRoute
  ImagesRoute: typeof ImagesRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  WriteRoute: typeof WriteRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  RegisterGoogleRoute: typeof RegisterGoogleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/write': {
      id: '/write'
      path: '/write'
      fullPath: '/write'
      preLoaderRoute: typeof WriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/images': {
      id: '/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof ImagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts': {
      id: '/drafts'
      path: '/drafts'
      fullPath: '/drafts'
      preLoaderRoute: typeof DraftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/google': {
      id: '/register/google'
      path: '/register/google'
      fullPath: '/register/google'
      preLoaderRoute: typeof RegisterGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DraftsRoute: DraftsRoute,
  ImagesRoute: ImagesRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  WriteRoute: WriteRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  RegisterGoogleRoute: RegisterGoogleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
